services:
  - type: web
    name: coco-bambu-avaliacao
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.main:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: mysql+pymysql://usuario:senha@host/banco